version: '3.2'
services:
  generate-password:
    container_name: generate-password
    image: generate-password:2022-10-22--01-38
    networks:
      - generate-password-network
    depends_on:
      - generate-password-database-mongodb
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'

  generate-password-database-mongodb:
    image: mongo:5.0.0
    container_name: generate-password-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user123
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    networks:
      - generate-password-network
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/generate-password --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  generate-password-network:
    driver: bridge

